"""Updated auto datetime on models for new history entry

Revision ID: f05685b1eb6f
Revises: 660c0aed766f
Create Date: 2023-11-04 13:34:14.765238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05685b1eb6f'
down_revision = '660c0aed766f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.alter_column('search_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.alter_column('search_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
